#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

echo "run Allwmake ThermoModel"
./thermoModel/Allwmake

echo "clean build"
wclean sigma
wclean myrhoPimpleFoam

echo "build targets"
wmake sigma
wmake myrhoPimpleFoam


#-----------------------------------------------------------------------------
